const lyrics = [
  { time: 14.5, text: "(When this began)" },
  { time: 17.5, text: "I had nothing to say" },
  { time: 20.0, text: "And I get lost in the nothingness inside of me" },
  { time: 23.5, text: "(I was confused)" },
  { time: 26.0, text: "And I let it all out to find" },
  { time: 29.0, text: "That I'm not the only person with these things in mind" },
  { time: 32.5, text: "(Inside of me)" },
  { time: 34.5, text: "But all the vacancy the words revealed" },
  { time: 38.0, text: "Is the only real thing that I've got left to feel" },
  { time: 41.5, text: "(Nothing to lose)" },
  { time: 43.5, text: "Just stuck, hollow and alone" },
  { time: 46.5, text: "And the fault is my own" },
  { time: 48.5, text: "And the fault is my own" },
  { time: 51.5, text: "I wanna heal, I wanna feel" },
  { time: 54.0, text: "What I thought was never real" },
  { time: 56.5, text: "I wanna let go of the pain I've felt so long" },
  { time: 59.5, text: "(Erase all the pain 'til it's gone)" },
  { time: 62.0, text: "I wanna heal, I wanna feel" },
  { time: 64.5, text: "Like I'm close to something real" },
  { time: 67.5, text: "I wanna find something I've wanted all along" },
  { time: 70.5, text: "Somewhere I belong" },
  { time: 75.0, text: "And I've got nothing to say" },
  { time: 78.0, text: "I can't believe I didn't fall right down on my face" },
  { time: 81.5, text: "(I was confused)" },
  { time: 83.5, text: "Looking everywhere only to find" },
  { time: 86.5, text: "That it's not the way I had imagined it all in my mind" },
  { time: 90.0, text: "(So what am I?)" },
  { time: 92.0, text: "What do I have but negativity?" },
  { time: 95.5, text: "'Cause I can't justify the way everyone is looking at me" },
  { time: 99.0, text: "(Nothing to lose)" },
  { time: 101.5, text: "Nothing to gain, hollow and alone" },
  { time: 104.5, text: "And the fault is my own" },
  { time: 106.5, text: "And the fault is my own" },
  { time: 109.0, text: "I wanna heal, I wanna feel" },
  { time: 112.0, text: "What I thought was never real" },
  { time: 114.5, text: "I wanna let go of the pain I've felt so long" },
  { time: 117.5, text: "(Erase all the pain 'til it's gone)" },
  { time: 120.0, text: "I wanna heal, I wanna feel" },
  { time: 122.5, text: "Like I'm close to something real" },
  { time: 125.5, text: "I wanna find something I've wanted all along" },
  { time: 128.5, text: "Somewhere I belong" },
  { time: 133.5, text: "I will never know myself until I do this on my own" },
  { time: 138.5, text: "And I will never feel anything else until my wounds are healed" },
  { time: 144.5, text: "I will never be anything 'til I break away from me" },
  { time: 150.0, text: "I will break away, I'll find myself today" },
  { time: 156.0, text: "I wanna heal, I wanna feel" },
  { time: 159.0, text: "What I thought was never real" },
  { time: 161.5, text: "I wanna let go of the pain I've felt so long" },
  { time: 164.5, text: "(Erase all the pain 'til it's gone)" },
  { time: 167.0, text: "I wanna heal, I wanna feel" },
  { time: 169.5, text: "Like I'm close to something real" },
  { time: 172.5, text: "I wanna find something I've wanted all along" },
  { time: 175.5, text: "Somewhere I belong" },
  { time: 181.5, text: "I wanna heal, I wanna feel like I'm somewhere I belong" },
  { time: 192.5, text: "I wanna heal, I wanna feel like I'm somewhere I belong" },
  { time: 202.5, text: "Somewhere I belong" }
];
console.log(JSON.stringify(lyrics));
