/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  theme: {
    extend: {
      colors: {
        background: '#131317',
        surface: '#131317',
        'surface-dim': '#131317',
        'surface-bright': '#39393e',
        'surface-container-lowest': '#0e0e12',
        'surface-container-low': '#1b1b20',
        'surface-container': '#1f1f24',
        'surface-container-high': '#2a292e',
        'surface-container-highest': '#353439',
        'on-surface': '#e4e1e8',
        'on-surface-variant': '#cec2d3',
        'inverse-surface': '#e4e1e8',
        'inverse-on-surface': '#303035',
        outline: '#978d9d',
        'outline-variant': '#4c4452',
        'surface-tint': '#deb7ff',
        primary: '#deb7ff',
        'on-primary': '#4a0080',
        'primary-container': '#55108d',
        'on-primary-container': '#c689ff',
        'inverse-primary': '#7c40b4',
        secondary: '#c7bfff',
        'on-secondary': '#2c1290',
        'secondary-container': '#4635a9',
        'on-secondary-container': '#b8afff',
        tertiary: '#cebdff',
        'on-tertiary': '#37206f',
        'tertiary-container': '#412b7a',
        'on-tertiary-container': '#ad97ed',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        
        // Brand & Style specifically mentioned in the prompt
        canvas: '#08080C',
        'surface-1': '#0E0F17',
        'surface-2': '#161726',
        'brand-primary': '#55108d',
        'brand-secondary': '#2d1491',
        'brand-tertiary': '#3A0864',
        'brand-accent': '#8a3dc6',
        'brand-highlight': '#22045b',
      },
      fontFamily: {
        sora: ['Sora', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
        jetbrains: ['JetBrains Mono', 'monospace'],
        playfair: ['"Playfair Display"', 'serif'],
      },
      spacing: {
        'gutter': '1.5rem',
        'margin': '2rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2.5rem',
      },
      keyframes: {
        'bounce-x': {
          '0%, 100%': {
            transform: 'translateX(25%)',
            animationTimingFunction: 'cubic-bezier(0.8, 0, 1, 1)',
          },
          '50%': {
            transform: 'translateX(0)',
            animationTimingFunction: 'cubic-bezier(0, 0, 0.2, 1)',
          },
        },
      },
      animation: {
        'bounce-x': 'bounce-x 1s infinite',
      },
    },
  },
  plugins: [],
}
